### ISSUE TITLE
Roadmap - Próximas alterações

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/greenbook#1]
- [ ] alterar background para creme
- [ ] adicionar relacionamento de sintomas (ansiedade, pirose, azia, tosse) um sintomas pode estar relacionado com várias plantas. se um sintoma tiver relação com uma das atuações da planta, deve ser mostrada
- [ ] Criar analogias entre efeito medicamentosos, por exemplo: efeito vasomotor é sinonimo de hipotensor
- [ ] Na busca por fitocomplexos, realizar análise combinatória para mostrar resultados combinados.
- [ ] Criar campo de colaboração para gerar issues no github https://docs.github.com/pt/rest/issues/issues?apiVersion=2022-11-28#create-an-issue
- [ ] CALC IA RX-FITO (configurações FITO-IA: peso, idade) As sugestões Fito-IA podem ser imprecisas, devem ser revisadas por um profissional capacitado antes de sua aplicação.
